package host:storage;

interface collection {
    // Documents and filters are JSON bytes.
    // The host converts JSON to/from its backend format (e.g. BSON for MongoDB).
    type document = list<u8>;

    // A handle to a named collection.
    resource connection {
        open: static func(name: string) -> connection;
    }

    count:       func(c: borrow<connection>) -> u64;
    find-all:    func(c: borrow<connection>) -> list<document>;
    find-one:    func(c: borrow<connection>, filter: document) -> option<document>;
    find:        func(c: borrow<connection>, filter: document) -> list<document>;
    insert-one:  func(c: borrow<connection>, doc: document);
    insert-many: func(c: borrow<connection>, docs: list<document>);

    // Update the first document matching `filter`
    update-one:  func(c: borrow<connection>, filter: document, update: document, upsert: bool);
}
