package hotel:reservation-wasm;

world reservation-world {
    include wasi:cli/imports@0.2.0;
    import hotel:store/reservation-store;
    import cache:keyvalue/keyvalue;
    export hotel:api/reservation;
}

world reservation-host-world {
    import hotel:store/reservation-store;
    import cache:keyvalue/keyvalue;
    export hotel:api/reservation;
}

world reservation-composed-host-world {
    import hotel:store/numbers-col;
    import hotel:store/reservations-col;
    export hotel:api/reservation;
}
