package hotel:attractions-data-wasm;

world attractions-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/attractions-store;
}

world attractions-store-host-world {
    import host:storage/collection;
    export hotel:store/attractions-store;
}
