package hotel:api;

interface geo {
    init: func();
    nearby: func(lat: f64, lon: f64) -> list<string>;
}

interface rate {
    record room-type {
        bookable-rate:        f64,
        code:                 string,
        room-description:     string,
        total-rate:           f64,
        total-rate-inclusive: f64,
    }
    record rate-plan {
        hotel-id:  string,
        code:      string,
        in-date:   string,
        out-date:  string,
        room-type: room-type,
    }
    init: func();
    get-rates: func(hotel-ids: list<string>, in-date: string, out-date: string) -> list<rate-plan>;
}

interface search {
    init: func();
    nearby: func(lat: f64, lon: f64, in-date: string, out-date: string) -> list<string>;
}

interface profile {
    record hotel {
        id:          string,
        name:        string,
        phone-number: string,
        description: string,
        addr:        address,
        images:      list<image>,
    }
    record address {
        street-number: string,
        street-name:   string,
        city:          string,
        state:         string,
        country:       string,
        postal-code:   string,
        lat:           f64,
        lon:           f64,
    }
    record image {
        url:     string,
        default: bool,
    }
    init: func();
    get-profiles: func(hotel-ids: list<string>) -> list<hotel>;
}

interface user {
    init: func();
    check-user: func(username: string, password: string) -> bool;
}

interface review {
    record image {
        url:     string,
        default: bool,
    }
    record review-comm {
        review-id:   string,
        hotel-id:    string,
        name:        string,
        rating:      f32,
        description: string,
        image:       image,
    }
    init: func();
    get-reviews: func(hotel-id: string) -> list<review-comm>;
}

interface attractions {
    init: func();
    nearby-rest:   func(hotel-id: string) -> list<string>;
    nearby-mus:    func(hotel-id: string) -> list<string>;
    nearby-cinema: func(hotel-id: string) -> list<string>;
}

interface reservation {
    init: func();
    check-availability: func(
        hotel-ids:   list<string>,
        in-date:     string,
        out-date:    string,
        room-number: s32,
    ) -> list<string>;
    make-reservation: func(
        hotel-id:      string,
        customer-name: string,
        in-date:       string,
        out-date:      string,
        room-number:   s32,
    ) -> list<string>;
}

interface recommendation {
    enum requirement {
        distance,
        rate,
        price,
    }
    init: func();
    recommend: func(
        requirement: requirement,
        lat: f64,
        lon: f64,
    ) -> list<string>;
}
