package hotel:recommendation-data-wasm;

world recommendation-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/recommendation-store;
}

world recommendation-store-host-world {
    import host:storage/collection;
    export hotel:store/recommendation-store;
}
