package hotel:geo-wasm;

world geo-world {
    include wasi:cli/imports@0.2.0;
    import hotel:store/geo-store;
    export hotel:api/geo;
}

world geo-host-world {
    import hotel:store/geo-store;
    export hotel:api/geo;
}

world geo-composed-host-world {
    import host:storage/collection;
    export hotel:api/geo;
}
