package hotel:reservation-data-wasm;

world reservation-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/reservation-store;
}

world reservation-store-host-world {
    import host:storage/collection;
    export hotel:store/reservation-store;
}
