package hotel:profile-data-wasm;

world profile-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/profile-store;
}

world profile-store-host-world {
    import host:storage/collection;
    export hotel:store/profile-store;
}
