package hotel:review-data-wasm;

world review-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/review-store;
}

world review-store-host-world {
    import host:storage/collection;
    export hotel:store/review-store;
}
