package hotel:geo-data-wasm;

world geo-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/geo-store;
}

world geo-store-host-world {
    import host:storage/collection;
    export hotel:store/geo-store;
}
