[package]
name = "recommendation-store-host"
version = "0.1.0"
edition = "2021"

[dependencies]
host-lib      = { path = "../../host-lib" }
wasmtime      = { version = "29", features = ["component-model", "async"] }
wasmtime-wasi = "29"
mongodb       = "3"
bson          = "2"
tonic         = { version = "0.12", features = ["transport"] }
tokio         = { version = "1", features = ["full"] }
anyhow        = "1"
