package hotel:attractions-wasm;

world attractions-world {
    include wasi:cli/imports@0.2.0;
    import hotel:store/attractions-store;
    export hotel:api/attractions;
}

world attractions-host-world {
    import hotel:store/attractions-store;
    export hotel:api/attractions;
}
