package hotel:search-wasm;

world search-world {
    include wasi:cli/imports@0.2.0;
    import hotel:api/geo;
    import hotel:api/rate;
    export hotel:api/search;
}

world search-host-world {
    import hotel:api/geo;
    import hotel:api/rate;
    export hotel:api/search;
}
