syntax = "proto3";

package profile_store;

service ProfileStore {
  rpc LoadProfiles(LoadProfilesRequest) returns (LoadProfilesResponse);
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
}

message LoadProfilesRequest {}
message LoadProfilesResponse {
  repeated Hotel profs = 1;
}

message GetProfileRequest {
  string id = 1;
}
message GetProfileResponse {
  Hotel prof = 1;
  bool found = 2;
}

message Hotel {
  string id = 1;
  string name = 2;
  string phoneNumber = 3;
  string description = 4;
  Address address = 5;
  repeated Image images = 6;
}

message Address {
  string streetNumber = 1;
  string streetName = 2;
  string city = 3;
  string state = 4;
  string country = 5;
  string postalCode = 6;
  float lat = 7;
  float lon = 8;
}

message Image {
  string url = 1;
  bool default = 2;
}