syntax = "proto3";
package reservation_store;

service ReservationStore {
  rpc LoadNumbers(LoadNumbersRequest)         returns (LoadNumbersResponse);
  rpc LoadReservations(LoadReservationsRequest) returns (LoadReservationsResponse);
  rpc InsertReservation(InsertReservationRequest) returns (InsertReservationResponse);
  rpc GetNumber(GetNumberRequest)             returns (GetNumberResponse);
  rpc GetReservations(GetReservationsRequest) returns (GetReservationsResponse);
  rpc GetNumbers(GetNumbersRequest)           returns (GetNumbersResponse);
}

message GetNumberRequest { string hotelId = 1; }
message GetNumberResponse { NumberRec num = 1; bool found = 2; }
message GetNumbersRequest  { repeated string hotelIds = 1; }
message GetNumbersResponse { repeated NumberRec numbers = 1; }
message GetReservationsRequest {
  string hotelId = 1;
  string inDate  = 2;
  string outDate = 3;
}
message GetReservationsResponse { repeated ReservationRec reservations = 1; }

message LoadNumbersRequest      {}
message LoadReservationsRequest {}
message InsertReservationRequest {
  string hotelId      = 1;
  string customerName = 2;
  string inDate       = 3;
  string outDate      = 4;
  uint32 number       = 5;
}
message InsertReservationResponse {}

message NumberRec {
  string hotelId       = 1;
  uint32 numberOfRoom  = 2;
}
message ReservationRec {
  string hotelId       = 1;
  string customerName  = 2;
  string inDate        = 3;
  string outDate       = 4;
  uint32 number        = 5;
}
message LoadNumbersResponse      { repeated NumberRec      numbers      = 1; }
message LoadReservationsResponse { repeated ReservationRec reservations = 1; }
