package hotel:user-data-wasm;

world user-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/user-store;
}

world user-store-host-world {
    import host:storage/collection;
    export hotel:store/user-store;
}
