package hotel:review-wasm;

world review-world {
    include wasi:cli/imports@0.2.0;
    import hotel:store/review-store;
    import cache:keyvalue/keyvalue;
    export hotel:api/review;
}

world review-host-world {
    import hotel:store/review-store;
    import cache:keyvalue/keyvalue;
    export hotel:api/review;
}

world review-composed-host-world {
    import host:storage/collection;
    import cache:keyvalue/keyvalue;
    export hotel:api/review;
}
