package hotel:rate-data-wasm;

world rate-store-world {
    include wasi:cli/imports@0.2.0;
    import host:storage/collection;
    export hotel:store/rate-store;
}

world rate-store-host-world {
    import host:storage/collection;
    export hotel:store/rate-store;
}
