[overrides]
"hotel:api"      = { path = "../../wit/hotel" }
"hotel:store"    = { path = "../../wit/hotel-store" }
"cache:keyvalue" = { path = "../../wit/cache" }
"host:storage"   = { path = "../../wit/host-storage" }
