package hotel:user-wasm;

world user-world {
    include wasi:cli/imports@0.2.0;
    import hotel:store/user-store;
    export hotel:api/user;
}

world user-host-world {
    import hotel:store/user-store;
    export hotel:api/user;
}

world user-composed-host-world {
    import host:storage/collection;
    export hotel:api/user;
}
